server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          default-label: "" # TODO
          uri: "" # TODO
          search-paths: config-data
  application:
    name: config-server
